table Tabla_Medidas
	lineageTag: d3a12703-a25c-4e96-94d2-d7edf983bde3

	measure Fact_liquida = sum(VentasFact[Valor Total c/ Descuento])
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: ac4fd303-0256-46ad-9efa-ac83e7e82985

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Costos = sum(VentasFact[Costo Total])
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 51d3c199-389c-43a4-b4fa-1a2827445e12

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure lucho_ganancias = sum(VentasFact[Utilidad])
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 0fc91808-a86d-4c62-95e9-500768812a51

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Margen% =
			
			DIVIDE([lucho_ganancias],[Fact_liquida])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4022cb79-685d-4a1b-b954-f357c01552ab

	measure Descuento = SUM(VentasFact[Descuento])
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 0652d824-0d76-4da6-bfde-a50314892f9e

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure 'Facturacion Media' = DIVIDE([Fact_liquida],DISTINCTCOUNT(VentasFact[Fecha]))
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 2f9b1c40-c9e7-44a7-a69a-bfe0b554efd5

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure EJEMPLO = SUM(VentasFact[Valor Total])
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 502a4a4a-50dd-4ff3-9204-db75bd012279

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	partition Tabla_Medidas = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

