name: Agente_Sincronizacion_Gala

on:
  push:
    branches:
      - main

# Aquí agregamos la "vitamina" para que no dé advertencias
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  notificar_fabric:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Descargando archivos
        uses: actions/checkout@v4 # Podés dejar la v4, con el ENV de arriba se arregla

      - name: 🤖 Activando Agente
        run: |
          echo "¡Agente ejecutado con éxito!"